builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin    
    goarch:
      - amd64     
      - arm64     
    binary: animux

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://github.com/VinylStage/animux-like
    description: A terminal virtual pet CLI.
    maintainer: Your Name <your.email@example.com>
    license: MIT
    formats:
      - deb

snapcrafts:
  - name: animux-like
    name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: A terminal virtual pet CLI.
    description: A terminal virtual pet CLI application.
    publish: true
    grade: stable
    confinement: classic
    apps:
      animux:
        command: animux

brews:
  - repository:
      owner: VinylStage
      name: animux-like
    directory: Formula
    homepage: "https://github.com/VinylStage/animux-like"
    description: "A terminal virtual pet CLI."
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
